version: "3"
services:
  db:
    restart: always
    image: "postgres:11"
    ports:
      - "5342:5342"

  backend:
    build: ./backend/
    ports:
      - "7999:7999"
    command: ["./wait-for-it.sh", "db:5342", "--", "./docker-entrypoint.sh"]

  frontend:
    build: ./frontend/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - backend
